// ==UserScript==
// @ScriptName        google自动翻页
// @Author            @langkhach270389, modified by Cuttlefish
// @UpdateTime        2024-01-01
// @ScriptURL         https://github.com/ByteTimes/FilterRules/raw/Rules/Rewrite/Html/EndlessGoogle.conf
// ==/UserScript==

hostname = www.google.*,

^https?:\/\/www\.google\..*\/search url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/endlessgoogle.js
