// ==UserScript==
// @ScriptName        哔哩哔哩繁体CC字幕转中文简体
// @UpdateTime        2023-04-13
// @Suitable          自行观看“# > ”注释内容
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.12
// @ScriptURL         https://github.com/ByteTimes/FilterRules/raw/Rules/Rewrite/ExtraRules/Bilibili_CC.conf
// ==/UserScript==


hostname = aisubtitle.hdslb.com,i0.hdslb.com

# > 哔哩哔哩繁体CC字幕转中文简体（2023-04-11）@ddgksf2013
^https?:\/\/.*\.hdslb\.com\/bfs\/subtitle\/.+\.json url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/bilibili_cc.js
