hostname = *.apple.com,*.cdn-apple.com

# 禁止OTA更新
^https?:\/\/mesu\.apple\.com url reject
^https?:\/\/appldnld\.apple\.com url reject
^https?:\/\/gdmf\.apple\.com url reject
^https?:\/\/gg\.apple\.com url reject
^https?:\/\/gs\.apple\.com url reject
^https?:\/\/ig\.apple\.com url reject
^https?:\/\/updates\.cdn-apple\.com url reject
^https?:\/\/updates-http\.cdn-apple\.com url reject
^https?:\/\/xp\.apple\.com url reject

