hostname = pan.baidu.com, afd.baidu.com
https?:\/\/pan\.baidu\.com\/api\/getconfig url reject-dict
https?:\/\/afd\.baidu\.com\/afd\/entry url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/bdcloud.js
https?:\/\/.*baidu\.com\/rest\/.*\/membership\/(proxy\/)?guide url reject-200
https?:\/\/pan\.baidu\.com\/act\/v\d\/(bchannel|welfare)\/list url reject-200
https?:\/\/pan\.baidu\.com\/rest\/.*\/pcs\/ad url reject-200
https?:\/\/pan\.baidu\.com\/act\/api\/activityentry url reject-200
https:\/\/pan\.baidu\.com\/rest\/.*\/membership\/user\?method=gamecenter url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/bdcloud.js
https:\/\/pan\.baidu\.com\/feed\/hotlist url reject-200
https?:\/\/.*zhangyuyidong\.cn\/api\/zysdk url reject-200
https?:\/\/pan\.baidu\.com\/api\/getsyscfg url reject-dict
https:\/\/pan\.baidu\.com\/queryintent\/queryhint url reject-200
https:\/\/pan\.baidu\.com\/coins\/center\/notice url reject-200
https:\/\/pan\.baidu\.com\/feed\/cardinfos url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/bdcloud.js
https:\/\/pan\.baidu\.com\/api\/taskscore\/tasklist url jsonjq-response-body '.result.list=[]'
https:\/\/pan\.baidu\.com\/recommend\/shortseries\/list url reject-dict

