// ==UserScript==
// @ScriptName        彩云天气净化     
// @Function          如果有需要的去除广告的APP，可自行在共享表格中添加需求
// @AddRequest        https://bit.ly/addRequestforAdBlock
// @UpdateTime        2024-09-27
// @Suitable          自行观看“# > ”注释内容
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.8
// @ScriptURL         https://github.com/ByteTimes/FilterRules/raw/Rules/Rewrite/AdBlock/CaiYunAds.conf
// ==/UserScript==

#若有彩云天气会员需求，请自行抓包旧版[ ≤ 7.20.2 ]使用，并添加MITM [ biz.cyapi.cn ]

hostname = wrapper.cyapi.cn, api.caiyunapp.com, starplucker.cyapi.cn, ad.cyapi.cn

# > 伪装VIP解锁48小时降水[需登录][新验证接口][需旧版≤ 7.20.2]
^https?:\/\/biz\.cyapi\.cn\/api\/v\d\/user_detail url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/caiyun_json.js
# > 伪装VIP解锁48小时降水[需登录][需旧版≤ 7.20.2]
^https?:\/\/biz\.cyapi\.cn\/v\d\/user url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/caiyun_json.js
# > 图层推广
^https?:\/\/wrapper\.cyapi\.cn\/v\d\/activity url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/caiyun_json.js
# > 活动推广
^https?:\/\/api\.caiyunapp\.com\/v\d\/activity url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/caiyun_json.js
# > 首页顶部推广
^https?:\/\/starplucker\.cyapi\.cn\/v\d/operation/homefeatures url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/caiyun_json.js
# > SVIP提醒推广
^https?:\/\/starplucker\.cyapi\.cn\/v\d/notification/message_center url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/caiyun_json.js
# > 雨季特惠提醒
^https?:\/\/starplucker\.cyapi\.cn\/v\d/config/cypage url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/caiyun_json.js
# > 发现页信息流推荐
^https?:\/\/starplucker\.cyapi\.cn\/v\d/operation/feeds url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/caiyun_json.js
# > 发现页banners
^https?:\/\/starplucker\.cyapi\.cn\/v\d/operation/banners url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/caiyun_json.js
# > 发现页中间部分
^https?:\/\/starplucker\.cyapi\.cn\/v\d/operation/features url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/caiyun_json.js
# > 发现页活动
^https?:\/\/starplucker\.cyapi\.cn\/v\d/campaigns url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/caiyun_json.js
# > 通用广告请求
^https?:\/\/ad\.cyapi\.cn\/v\d url reject-200
