hostname = *.snssdk.com,*.pangolin-sdk-toutiao.com,*.pangolin-sdk-toutiao-b.com,*.pangolin-sdk-toutiao1.com,*.pstatp.com,*.pglstatp-toutiao.com,*.byteimg.com,gurd.snssdk.com

# 番茄小说 穿山甲广告SDK
^https?:\/\/.+\.pangolin-sdk-toutiao\.com\/api\/ad\/union\/sdk\/(get_ads|stats|settings)\/ - reject
^https?:\/\/.+\.pangolin-sdk-toutiao-b\.com\/api\/ad\/union\/sdk\/(get_ads|stats|settings)\/ - reject
^https?:\/\/.+\.pangolin-sdk-toutiao1\.com\/api\/ad\/union\/sdk\/(get_ads|stats|settings)\/ - reject
# 广告图片广告包
^https?:\/\/.+\.(pglstatp-toutiao|pstatp)\.com\/(obj|img)\/(ad-app-package|ad)\/.+ - reject
# snssdk广告API
^https?:\/\/.+\.snssdk\.com\/api\/ad\/.+ - reject
# 广告视频物料
^https?:\/\/.+\.pglstatp-toutiao\.com\/.+\/toutiao\.mp4 - reject
^https?:\/\/.+\.(pglstatp-toutiao|pstatp)\.com\/(obj|img)\/web\.business\.image\/.+ - reject
^https?:\/\/.+\.(pglstatp-toutiao|pstatp)\.com\/obj\/ad-pattern\/renderer - reject
^https?:\/\/gurd\.snssdk\.com\/src\/server\/v3\/package - reject
^https?:\/\/.+\.byteimg.com/tos-cn-i-1yzifmftcy\/(.+)-jpeg\.jpeg - reject
# ^https?:\/\/.+\.pstatp\.com\/obj\/mosaic-legacy\/.+\?from\=ad - reject
# ^https?:\/\/.+\.pstatp\.com\/bytecom\/resource\/track-log\/src\/.+ - reject
^https?:\/\/.+\.snssdk\.com\/video\/play\/1\/toutiao\/.+\/mp4 - reject
^http:\/\/.+\.byteimg\.com\/ad-app-package - reject
^http:\/\/.+\.byteimg\.com\/web\.business\.image - reject
^https?:\/\/.+?\.snssdk\.com\/motor\/operation\/activity\/display\/config\/V2\/ - reject

