[rewrite]
# 番茄小说 穿山甲广告SDK
^https?:\/\/.+\.pangolin-sdk-toutiao\.com\/api\/ad\/union\/sdk\/(get_ads|stats|settings)\/ - reject
^https?:\/\/.+\.pangolin-sdk-toutiao-b\.com\/api\/ad\/union\/sdk\/(get_ads|stats|settings)\/ - reject
^https?:\/\/.+\.pangolin-sdk-toutiao1\.com\/api\/ad\/union\/sdk\/(get_ads|stats|settings)\/ - reject
# 广告图片广告包
^https?:\/\/.+\.(pglstatp-toutiao|pstatp)\.com\/(obj|img)\/(ad-app-package|ad)\/.+ - reject
# snssdk广告API
^https?:\/\/.+\.snssdk\.com\/api\/ad\/.+ - reject
# 广告视频物料
^https?:\/\/.+\.pglstatp-toutiao\.com\/.+\/toutiao\.mp4 - reject
^https?:\/\/.+\.(pglstatp-toutiao|pstatp)\.com\/(obj|img)\/web\.business\.image\/.+ - reject
^https?:\/\/.+\.(pglstatp-toutiao|pstatp)\.com\/obj\/ad-pattern\/renderer - reject
^https?:\/\/gurd\.snssdk\.com\/src\/server\/v3\/package - reject
^https?:\/\/.+\.byteimg.com/tos-cn-i-1yzifmftcy\/(.+)-jpeg\.jpeg - reject
^https?:\/\/.+\.pstatp\.com\/obj\/mosaic-legacy\/.+\?from\=ad - reject
^https?:\/\/.+\.pstatp\.com\/bytecom\/resource\/track-log\/src\/.+ - reject
^https?:\/\/.+\.snssdk\.com\/video\/play\/1\/toutiao\/.+\/mp4 - reject
^http:\/\/.+\.byteimg\.com\/ad-app-package - reject
^http:\/\/.+\.byteimg\.com\/web\.business\.image - reject
^https?:\/\/.+?\.snssdk\.com\/motor\/operation\/activity\/display\/config\/V2\/ - reject

[rule]
#放行听书
DOMAIN-KEYWORD,tts,DIRECT
DOMAIN-SUFFIX,byteimg.com,DIRECT
#广告精确域名
DOMAIN,i.snssdk.com,REJECT
DOMAIN,i-lq.snssdk.com,REJECT
DOMAIN,is.snssdk.com,REJECT
DOMAIN,mcs.snssdk.com,REJECT
DOMAIN,p3-aio.ecombdimg.com,REJECT
DOMAIN,p26-item.ecombdimg.com,REJECT
DOMAIN,p6-ad-sign.byteimg.com,REJECT
DOMAIN,p9-ad-sign.byteimg.com,REJECT
DOMAIN,dig.bdurl.net,REJECT
DOMAIN,activity-ag.awemeughun.com,REJECT
DOMAIN,tnc3-alisc1.snssdk.com,REJECT
DOMAIN,tnc3-aliec2.snssdk.com,REJECT
DOMAIN,security-lq.snssdk.com,REJECT
DOMAIN,sf3-ttcdn-tos.pstatp.com,REJECT
DOMAIN,msync-im1-vip6-std.easemob.com,REJECT
DOMAIN,ad.zijieapi.com,REJECT
DOMAIN,scc.bytedance.com,REJECT
DOMAIN,csj-sp.csjdeveloper.com,REJECT
#广告后缀域名
DOMAIN-SUFFIX,fqnovelvod.com,REJECT
DOMAIN-SUFFIX,dragonread.com,REJECT
DOMAIN-SUFFIX,ecombdimg.com,REJECT
DOMAIN-SUFFIX,luckycat.byteimg.com,REJECT
DOMAIN-SUFFIX,pglstatp-toutiao.com,REJECT
DOMAIN-SUFFIX,byteorge.com,REJECT
DOMAIN-SUFFIX,bytegoofy.com,REJECT
DOMAIN-SUFFIX,pangolin-sdk-toutiao.com,REJECT
DOMAIN-SUFFIX,pangolin-sdk-toutiao-b.com,REJECT
DOMAIN-SUFFIX,pangolin-sdk-toutiao1.com,REJECT
DOMAIN-SUFFIX,novelapp.ixigua.com,REJECT
DOMAIN-SUFFIX,default.ixigua.com,REJECT
#广告关键词
DOMAIN-KEYWORD,magic.byteimg,REJECT
DOMAIN-KEYWORD,zijieapi,REJECT
DOMAIN-KEYWORD,applog,REJECT
DOMAIN-KEYWORD,luckycat,REJECT
DOMAIN-KEYWORD,ad-sign,REJECT
DOMAIN-KEYWORD,ad-app,REJECT
#IP黑名单
IP-CIDR,49.71.37.101/32,REJECT,no-resolve
IP-CIDR,117.71.105.23/32,REJECT,no-resolve
IP-CIDR,218.94.207.205/32,REJECT,no-resolve
IP-CIDR,117.92.229.188/32,REJECT,no-resolve
IP-CIDR,101.36.166.16/32,REJECT,no-resolve
IP-CIDR,180.96.2.114/32,REJECT,no-resolve

[mitm]
hostname = *.snssdk.com,*.pangolin-sdk-toutiao.com,*.pangolin-sdk-toutiao-b.com,*.pangolin-sdk-toutiao1.com,*.pstatp.com,*.pglstatp-toutiao.com,*.byteimg.com,gurd.snssdk.com
