// ==UserScript==
// @ScriptName        汽水音乐净化           
// @Function          如果有需要的去除广告的APP，可自行在共享表格中添加需求
// @AddRequest        https://bit.ly/addRequestforAdBlock
// @UpdateTime        2025-09-26
// @Suitable          自行观看“# > ”注释内容
// @Attention         使用前请卸载汽水音乐，挂载脚本然后使用
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.6
// @ScriptURL         https://github.com/ByteTimes/FilterRules/raw/Rules/Rewrite/AdBlock/QiShuiMusicAds.conf
// ==/UserScript==


hostname = beta-luna.douyin.com, api.qishui.com, tnc*-*.zijieapi.com

# > 视频广告
^https:\/\/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){1,3}\/luna\/media_ads url reject-200
# > 通用广告
^https:\/\/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){1,3}\/luna\/ads url reject-200
# > 位置隐私
^https:\/\/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){1,3}\/location\/info url reject-200
# > 广告弹窗
^https:\/\/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){1,3}\/luna\/commerce url reject-200
# > TAGS推荐
^https:\/\/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){1,3}\/luna\/hashtag\/recommend url reject-200
# > 我的页面推广
^https:\/\/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){1,3}\/luna\/me\? url jsonjq-response-body 'del(.reward_ad_banner)'
# > 会员免费听整月VIEW
^https:\/\/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){1,3}\/luna\/card url jsonjq-response-body 'del(.preview_guide)'
# > 热门搜索
^https:\/\/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){1,3}\/luna\/search-block url jsonjq-response-body 'del(.search_chart_block)'
# > DNS处理
^https:\/\/tnc.*zijieapi\.com\/get_domains url reject-200
# > 搜索界面活动
^https:\/\/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){1,3}\/luna\/activities url jsonjq-response-body 'del(.activity_map)'
# > 音乐流推广
^https:\/\/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){1,3}\/luna\/feed\/song-tab url jsonjq-response-body '.items |= map(select(.type == "track"))'
