// ==UserScript==
// @ScriptName        小宇宙FM去广告
// @UpdateTime        2025-09-26
// @Suitable          自行观看“# > ”注释内容
// @Version           V1.0.3
// @ScriptURL         https://github.com/ByteTimes/FilterRules/raw/Rules/Rewrite/AdBlock/XiaoYuZhouAds.conf
// ==/UserScript==

hostname = api.xiaoyuzhoufm.com, 118.31.123.175, 112.124.203.116, 118.31.125.171, 47.57.181.112, 47.57.182.96

# > 搜索推广
^https?:\/\/api\.xiaoyuzhoufm\.com\/v\d\/search\/get-express url reject-200
# > 搜索填词
^https?:\/\/api\.xiaoyuzhoufm\.com\/v\d\/search\/get-preset url reject-200
# > 搜索建议
^https?:\/\/api\.xiaoyuzhoufm\.com\/v\d\/category\/list-daily-suggestion url reject-200
# > 开屏广告
^https?:\/\/api\.xiaoyuzhoufm\.com\/v\d\/flash-screen\/list url reject-200
# > 首页信息流推广
^https?:\/\/api\.xiaoyuzhoufm\.com\/v\d\/discovery-feed\/list url jsonjq-response-body '.data |= map(select(.type != "DISCOVERY_BANNER"))'
