hostname = 118.89.204.198,103.41.167.237,2402:4e00:1200:ed00:0:9089:6dac:96b6,www.zhihu.com,api.zhihu.com,zhuanlan.zhihu.com,m-cloud.zhihu.com,page-info.zhihu.com,web-render.zhihu.com
^https?:\/\/118\.89\.204\.198 url reject-dict
^https?:\/\/103\.41\.167\.237 url reject-dict
^https?:\/\/2402:4e00:1200:ed00:0:9089:6dac:96b6 url reject-200
^https?:\/\/api\.zhihu\.com\/commercial_api url reject-dict
^https?:\/\/api\.zhihu\.com\/commercial_api\/answer/\d+/bottom-v2 url reject-dict
^https?:\/\/api\.zhihu\.com\/message-push\/event url reject-dict
^https?:\/\/api\.zhihu\.com\/guide_center\/strategy url reject-dict
^https?:\/\/api\.zhihu\.com\/bazaar\/float_window url reject-dict
^https?:\/\/api\.zhihu\.com\/metrics\/report url reject-dict
^https?:\/\/api\.zhihu\.com\/settings\/new\/notification url reject-dict
^https?:\/\/api\.zhihu\.com\/bazaar\/vip_tab\/header url reject-dict
^https?:\/\/api\.zhihu\.com\/(notifications\/v\d\/count) url reject-dict
^https?:\/\/api\.zhihu\.com\/root\/window url reject-dict
^https?:\/\/api\.zhihu\.com\/me\/guides url reject-dict
^https?:\/\/api\.zhihu\.com\/moments\/recent url reject-dict
^https?:\/\/api\.zhihu\.com\/api\/v4\/ecom_data\/config url reject-dict
^https?:\/\/api\.zhihu\.com\/feed\/render\/revisit\/tag_config url reject-dict
^https?:\/\/api\.zhihu\.com\/content-distribution-core\/sections\/ url reject-dict
^https?:\/\/api\.zhihu\.com\/people\/ url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https?:\/\/api\.zhihu\.com\/feed-root\/block url script-request-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https?:\/\/api\.zhihu\.com\/root\/tab\/v2 url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https:\/\/(api|web-render)\.zhihu\.com\/topstory\/recommend url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https:\/\/api\.zhihu\.com\/questions\/\d+\/feeds? url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https?:\/\/api\.zhihu\.com\/next-render url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https?:\/\/api\.zhihu\.com\/notifications\/v3\/(message|timeline\/entry\/system_message) url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https?:\/\/api\.zhihu\.com\/(comment_v5\/)?(answers|comments?|articles|pins)\/\d+\/(root_|child_)?comments? url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https:\/\/(page-info|api)\.zhihu\.com\/answers\/v2\/\d+ url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https:\/\/api\.zhihu\.com\/articles\/v\d\/\d+ url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https?:\/\/api\.zhihu\.com\/moments_v3\? url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https?:\/\/api\.zhihu\.com\/topstory\/hot-lists(\?|\/) url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https?:\/\/api\.zhihu\.com\/search\/preset_words\? url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https?:\/\/api\.zhihu\.com\/search\/recommend_query url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https:\/\/api\.zhihu\.com\/settings\/blocked_users url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
^https?:\/\/www\.zhihu\.com\/api\/v4\/comment_v5\/answers\/\d+\/abstract_comment\? url script-response-body https://github.com/ByteTimes/FilterRules/raw/Rules/Scripts/zhihu.min.js
